---

# Adama QA VM (on rodeo)
host_name: adama-qa
ansible_host: 129.114.6.110
ansible_ssh_user: rodeo  
ansible_ssh_private_key_file: ~/.ssh/jgentle-tacc-rodeo.pem

config: 
  - section: server 
    option: url
    value: http://"{{ ansible_host }}"
  - section: server 
    option: bind
    value: 0.0.0.0:80
  - section: server 
    option: prefix
    value: 
  - section: server 
    option: api_prefix
    value: /community/v"{{ lookup('file', '../adama/VERSION') }}"
  - section: server 
    option: api_docs
    value: https://api.araport.org/community/v0.3
  - section: server 
    option: api_url
    value: https://api.araport.org
  - section: store 
    option: host
    value: localhost
  - section: store 
    option: port
    value: 6379
  - section: queue 
    option: host
    value: "{{ ansible_host }}"
  - section: queue 
    option: port
    value: 5672
  - section: docker 
    option: command
    value: docker
  - section: docker 
    option: host
    value: ""
  - section: server 
    option: swagger_ui
    value: http://"{{ ansible_host }}"/swagger-ui

nginx_server_name: "{{ host_name }}" 
self_sign: yes 
